// frontend/src/App.svelte
<script lang="ts">
  import NavBar from "./components/NavBar.svelte";
  import DashboardTab from "./tabs/DashboardTab.svelte";
  import SettingsTab from "./tabs/SettingsTab.svelte";

  let selected = "dashboard";

  function handleSelect(tab: string) {
    selected = tab;
  }
</script>

<div class="bg-[#101922] h-screen w-screen flex">
  <NavBar onselect={handleSelect} />
  <div class="bg-[#101922] flex-1">
    {#if selected === "dashboard"}
      <DashboardTab />
    {:else if selected === "network"}
      <div class="text-white p-8">Network Monitor</div>
    {:else if selected === "settings"}
      <SettingsTab />
    {:else if selected === "rules"}
      <div class="text-white p-8">Detection Rules</div>
    {:else if selected === "alerts"}
      <div class="text-white p-8">Alert Logs</div>
    {:else}
      <div class="text-white p-8">Dashboard</div>
    {/if}
  </div>
</div>

// frontend/src/App.tsx
import { useState } from "react";
import "./App.css";
import NavBar from "./components/NavBar";
import SettingsTab from "./tabs/SettingsTab";

function App() {
  const [selected, setSelected] = useState("dashboard");

  const handleSelectedChange = (data: string) => {
    setSelected(data);
  };

  const renderTab = () => {
    switch (selected) {
      case "dashboard":
        return "dashboard";
      case "network":
        return "network";
      case "settings":
        return <SettingsTab />;
      default:
        return "dashboard";
    }
  };
  return (
    <div className="bg-[#101922] h-screen w-screen flex">
      <NavBar onSelect={handleSelectedChange} />
      <div className="bg-[#101922] flex-1">{renderTab()}</div>
    </div>
  );
}

export default App;
